name: Continuous integration

on: [push, pull_request]

jobs:
  rustfmt:
    name: rustfmt / stable
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install rust
        run: |
          rustup update --no-self-update ${{ matrix.rust }}
          rustup component add rustfmt

      - name: cargo fmt
        run: |
          cargo fmt --all -- --check

  clippy:
    name: clippy / ${{ matrix.rust }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: stable
            rust: stable

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Install rust
        run: |
          rustup update --no-self-update ${{ matrix.rust }}
          rustup component add clippy

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  test:
    name: test / ${{matrix.name}}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: stable
            rust: stable
          - name: beta
            rust: beta
          - name: 1.45.2
            rust: 1.45.2

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install rust
        run: |
          rustup default ${{matrix.name}}
          rustup update --no-self-update ${{ matrix.rust }}

      - name: Update and install postfix  
        run: sudo DEBIAN_FRONTEND=noninteractive apt-get update; sudo DEBIAN_FRONTEND=noninteractive apt-get -y install postfix

      - name: Run smpt server
        run: smtp-sink 2525 1000&
      
      - name: Install cargo hack
        run: cargo install cargo-hack --debug

      - name: Test with cargo hack
        uses: actions-rs/cargo@v1
        with:
          command: hack
          args: test --each-feature
  
#  coverage:
#    name: Coverage
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions-rs/toolchain@v1
#        with:
#          toolchain: nightly
#          override: true
#      - run: sudo DEBIAN_FRONTEND=noninteractive apt-get -y install postfix
#      - run: smtp-sink 2525 1000&
#      - uses: actions-rs/cargo@v1
#        with:
#          command: test
#          args: --no-fail-fast
#        env:
#          CARGO_INCREMENTAL: "0"
#          RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads"
#      - id: coverage
#        uses: actions-rs/grcov@v0.1
#      - name: Coveralls upload
#        uses: coverallsapp/github-action@master
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          path-to-lcov: ${{ steps.coverage.outputs.report }}